title: Tama's Memory Game - Japanese
logo: /assets/img/logo2.png
description: Minimal is a theme for GitHub Pages.
repository: 404N0TAVAILABLE/minimal.git
show_downloads: true
google_analytics:
  #theme: jekyll-theme-minimal
